.TH "libnovaconfig" "1" "November 2007" "0.12.1"
.SH NAME
libnovaconfig - config helper for libnova development
.SH SYNOPSIS
.B libnovaconfig
[\fI--version\fR]
.SH DESCRIPTION
config program for libnova.
.br
prints usage without any options and returns -1
.SS "Generic options:"
.TP
\fB\-\-version\fR
Show libnova version
.SH SEE-ALSO
Upstream homepage
.TP 
http://libnova.sourceforge.net/index.html
.SH AUTHOR
libnovaconfig was written by Liam Girdwood
.PP
This manual page was written by Sune Vuorela <debian@pusling.com>,
for the Debian project (but may be used by others).
